### ISSUE TITLE
Move `ivory/serializer` from `require-dev` to `require`

### ISSUE THREAD

**Issue by Powerhamster** [bresam/ivory-google-map#17]
`ivory/serializer` is not a development only requirement. It is used inside `AbstractSerializableService`

**Comment by bresam** [comment]
Thats right, the original creator of this package included it to require-dev due to the fact that it is only used on some features of the package. It's possible to use several parts of the package without the serializer.

But i'm basically with you. It should be in require.
The very best solution would be to get rid of ivory/serializer and use the symfony/serializer.

I'm very busy in the next months, if you like to contribute feel free to make a PR. Would be glad to get some help on this.

**Comment by Chris53897** [comment]
`The very best solution would be to get rid of ivory/serializer and use the symfony/serializer.`
That is a good idea. Maintaining all the Repos, just for dev-tools to support symfony 6 or make other changes, just feels wrong.

**Comment by bresam** [comment]
replaced by symfony serializer in latest versions
