### ISSUE TITLE
Feature-Request: Geolocation

### ISSUE THREAD

**Issue by mariemchtourou** [bresam/ivory-google-map#3]
Hi!
I wanted to know if you included a way to get geolocation without JS. I am using Symfony and I want to get my current location on my controller.
Thank you!

**Comment by bresam** [comment]
Hi!
This package includes features around the Google API and Google Maps. According to my information Google does not offer geo-location tracking by IP address so I would not implement this in this package.
If I am wrong on this, I am open for further inputs and would put this on the road map accordingly.

Please let me know your thoughts.

**Comment by mariemchtourou** [comment]
I only saw this documentation: https://developers.google.com/maps/documentation/javascript/geolocation
But, it's in JS and I want to add it to my controller. Do you have a way around it?

**Comment by bresam** [comment]
As they refer in the docs what geolocation is and how it works, it's only possible on client side to get detailed geolocation  informations:
> W3C Geolocation standard
Applications that want to perform geolocation must support the W3C Geolocation standard. Notice that the sample code above determines the user's location through the W3C navigator.geolocation property.

> Some browsers use IP addresses to detect a user's location. However, it may only provide a rough estimate of a user's location. The W3C approach is the easiest and most fully-supported so it should be prioritized over other geolocation methods.

If you want to do this from server side, you have to use an API like [ipstack](https://ipstack.com/).
Such a function wont be supported by this package because it is off-topic.

Is this answer fine for you?

**Comment by mariemchtourou** [comment]
All good!
Thank you so much for your hard work!

**Comment by bresam** [comment]
Thank you.
